import React, { useEffect, useState } from 'react';
import { ShieldCheck, ShieldAlert, LogIn, ArrowRight } from 'lucide-react';
import { UserSession } from '../types';

interface LoginProps { onLogin: (user: UserSession) => void; isDarkMode: boolean; usersList?: UserSession[]; }
export const Login: React.FC<LoginProps> = () => {
  const [loading,setLoading]=useState(false); const [error,setError]=useState<string|null>(null);
  useEffect(()=>{const e=new URLSearchParams(window.location.search).get('auth_error');if(e)setError(decodeURIComponent(e));},[]);
  return <div className="min-h-screen flex flex-col justify-between bg-slate-50 text-slate-800">
    <header className="px-6 py-4 border-b border-slate-200 bg-white flex items-center justify-between"><div className="flex items-center gap-3"><div className="w-10 h-10 rounded-xl bg-[#0078D4] flex items-center justify-center text-white"><ShieldCheck className="w-5 h-5"/></div><div><div className="flex items-center gap-2"><span className="font-black text-xl tracking-tight text-[#0078D4]">INTERFLOW</span><span className="text-[10px] uppercase font-bold px-2 py-0.5 rounded bg-blue-50 text-blue-700 border border-blue-200">Microsoft Entra ID</span></div><p className="text-xs text-slate-500">Plateforme d'administration & gestion des profils</p></div></div><div className="text-xs font-medium text-slate-500 flex items-center gap-2"><ShieldCheck className="w-4 h-4 text-emerald-500"/> SSO sécurisé</div></header>
    <main className="flex-1 flex items-center justify-center p-6"><div className="w-full max-w-md bg-white p-8 rounded-3xl border border-slate-200 shadow-xl"><div className="text-center mb-8"><h1 className="text-3xl font-extrabold">Connexion InterFlow</h1><p className="mt-2 text-sm text-slate-500">Utilisez votre compte professionnel Microsoft Entra ID.</p></div>{error&&<div className="mb-5 p-3 rounded-xl bg-rose-50 border border-rose-200 text-rose-700 text-xs flex gap-2"><ShieldAlert className="w-4 h-4 shrink-0"/><span>{error}</span></div>}<button disabled={loading} onClick={()=>{setLoading(true);window.location.href='/api/auth/entra/login';}} className="w-full py-3.5 rounded-xl bg-[#0078D4] hover:bg-[#106ebe] text-white font-bold flex items-center justify-center gap-3 disabled:opacity-60">{loading?<div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin"/>:<LogIn className="w-4 h-4"/>}<span>{loading?'Redirection vers Microsoft…':'Se connecter avec Microsoft'}</span>{!loading&&<ArrowRight className="w-4 h-4"/>}</button><p className="text-[11px] text-slate-400 text-center mt-5">Le compte doit être habilité dans Microsoft Entra ID et InterFlow.</p></div></main>
    <footer className="px-6 py-3 border-t border-slate-200 bg-white text-center text-xs text-slate-500">© 2026 InterFlow — Authentification Microsoft Entra ID</footer>
  </div>;
};
