- name: Update packages
  apt:
    update_cache: yes

- name: Install dependencies
  apt:
    name:
      - docker.io
      - docker-compose-v2
      - git
    state: present

- name: Enable Docker
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Add azureuser to docker group
  user:
    name: azureuser
    groups: docker
    append: yes
