---
- name: Update packages
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install Docker packages
  ansible.builtin.apt:
    name:
      - docker.io
      - docker-compose-v2
    state: present

- name: Enable Docker
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started

- name: Add azureuser to docker group
  ansible.builtin.user:
    name: azureuser
    groups: docker
    append: true